### PR TITLE
v0.4.7

### PR DESCRIPTION
**Pull request by rolyatmax**

### CODE REVIEW

**Comment by paulgb** [comment]
Was this already pushed to npm? If not, I have a PR we can add before the bump (#46)

**Comment by rolyatmax** [comment]
Yeah, it was. We can bump the version again, though, haha

**Review by paulgb — APPROVED** [review]

**Comment by paulgb** [comment]
ok, I've approved this one, I'll let you pick the sequence of events :)

**Comment by rolyatmax** [comment]
Yeah, it was already too late :-( We already published v0.4.7 so we are forced to publish a new version for anything that comes after that.

**Pull request merged**
